name: "Install protobuf"
description: "Install protobuf and copies the protos from the 'common' repo to a dir named 'common'"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make
          make check           
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig
      - name: Copy proto files from common
        uses: actions/checkout@v2
        with:
          path: ./common
          repository: Seneca-AI/common
          token: ${{ secrets.CROSS_REPO_TOKEN }}