on:
  push:
    branches:
      - staging

name: Trigger integration test
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        run: |
          output=$(curl -i -H "Authorization: lSfsjS3nebraYqbzbpFS" http://34.95.3.199:5050/integration_test)
          echo $output
          if [[ $output != *"SUCCESS"* ]]; then
            exit 1
          fi
