on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

name: run tests
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout common repo
      uses: actions/checkout@v2
      with: 
        repository: Seneca-AI/common
        token: ${{ secrets.ADMIN_TOKEN_LUCA }}
        persist-credentials: true
    - name: Copy golang proto definitions into tmp folder
      run: |
        mkdir ~/tmp
        mkdir ~/tmp/proto_out
        cp -r ./proto_out/go/api/type/* ~/tmp/proto_out
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Copy proto definitions to this repo
      run: |
        cp -r ~/tmp/proto_out* ./api/type

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: go test ./... -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Calc coverage
      run: |
        go test ./... -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov