on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

name: run tests
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout common repo
      uses: actions/checkout@v2
      with: 
        repository: Seneca-AI/common
        token: ${{ secrets.ADMIN_TOKEN_LUCA }}
        persist-credentials: true
    - name: Upload golang proto definitions
      uses: actions/upload-artifact@v2
      with:
        name: proto-definitions-go
        path: proto_out/go/api/type/

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download golang proto definitions
      uses: actions/download-artifact@v2
      with:
        name: proto-definitions-go
        path: api/type/
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  unit-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download golang proto definitions
      uses: actions/download-artifact@v2
      with:
        name: proto-definitions-go
        path: api/type/
    - name: Run tests
      run: go test ./... -v -covermode=count

  unit-test-coverage:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download golang proto definitions
      uses: actions/download-artifact@v2
      with:
        name: proto-definitions-go
        path: api/type/
    - name: Calc coverage
      run: |
        go test ./... -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov